"""empty message

Revision ID: 19ad5d84c3f7
Revises: f2fc77413854
Create Date: 2026-05-21 11:50:08.098691

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19ad5d84c3f7'
down_revision = 'f2fc77413854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
