"""Add unique constraint to problem name

Revision ID: 4c9d8fdc15dc
Revises: a5e5daff334a
Create Date: 2026-05-26 12:15:13.858443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4c9d8fdc15dc'
down_revision = 'a5e5daff334a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_problem_name'), 'problem', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_name'), table_name='problem')
    # ### end Alembic commands ###
