"""add contestproblems and links

Revision ID: 6614c98703c1
Revises: 2aeb99679ffb
Create Date: 2026-05-20 12:05:36.492905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6614c98703c1'
down_revision = '2aeb99679ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contestproblems',
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contestproblems')
    # ### end Alembic commands ###
