"""empty message

Revision ID: 6c5f4bc848f0
Revises: 6614c98703c1
Create Date: 2026-05-20 15:42:03.774386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c5f4bc848f0'
down_revision = '6614c98703c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
