"""migrate_time_limit_to_numeric

Revision ID: a5e5daff334a
Revises: ad20d28a34ef
Create Date: 2026-05-25 11:56:44.765481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a5e5daff334a'
down_revision = 'ad20d28a34ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem', 'time_limit',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False,
               postgresql_using="REPLACE(time_limit, ',', '')::NUMERIC(10, 3)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem', 'time_limit',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="time_limit::VARCHAR")
    # ### end Alembic commands ###
