"""add submissions and ai battles

Revision ID: ace85548d58f
Revises: 4c9d8fdc15dc
Create Date: 2026-05-28 12:23:19.886935

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ace85548d58f'
down_revision = '4c9d8fdc15dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=True),
    sa.Column('participant_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('total_time_ms', sa.Integer(), nullable=True),
    sa.Column('peak_memory_kb', sa.Integer(), nullable=True),
    sa.Column('code_bytes', sa.Integer(), nullable=True),
    sa.Column('physical_lines', sa.Integer(), nullable=True),
    sa.Column('effective_lines', sa.Integer(), nullable=True),
    sa.Column('max_nesting_depth', sa.Integer(), nullable=True),
    sa.Column('analysis_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_contest_id'), 'submission', ['contest_id'], unique=False)
    op.create_index(op.f('ix_submission_participant_type'), 'submission', ['participant_type'], unique=False)
    op.create_index(op.f('ix_submission_problem_id'), 'submission', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submission_user_id'), 'submission', ['user_id'], unique=False)
    op.create_index(op.f('ix_submission_verdict'), 'submission', ['verdict'], unique=False)
    op.create_table('aibattle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=True),
    sa.Column('user_submission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aibattle_contest_id'), 'aibattle', ['contest_id'], unique=False)
    op.create_index(op.f('ix_aibattle_problem_id'), 'aibattle', ['problem_id'], unique=False)
    op.create_index(op.f('ix_aibattle_status'), 'aibattle', ['status'], unique=False)
    op.create_index(op.f('ix_aibattle_user_id'), 'aibattle', ['user_id'], unique=False)
    op.create_table('submissioncaseresult',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('case_index', sa.Integer(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('stdout_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stderr_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_stderr_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissioncaseresult_submission_id'), 'submissioncaseresult', ['submission_id'], unique=False)
    op.create_table('aibattleparticipant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('battle_id', sa.Uuid(), nullable=False),
    sa.Column('participant_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('generation_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('generation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['aibattle.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aibattleparticipant_battle_id'), 'aibattleparticipant', ['battle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aibattleparticipant_battle_id'), table_name='aibattleparticipant')
    op.drop_table('aibattleparticipant')
    op.drop_index(op.f('ix_submissioncaseresult_submission_id'), table_name='submissioncaseresult')
    op.drop_table('submissioncaseresult')
    op.drop_index(op.f('ix_aibattle_user_id'), table_name='aibattle')
    op.drop_index(op.f('ix_aibattle_status'), table_name='aibattle')
    op.drop_index(op.f('ix_aibattle_problem_id'), table_name='aibattle')
    op.drop_index(op.f('ix_aibattle_contest_id'), table_name='aibattle')
    op.drop_table('aibattle')
    op.drop_index(op.f('ix_submission_verdict'), table_name='submission')
    op.drop_index(op.f('ix_submission_user_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_problem_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_participant_type'), table_name='submission')
    op.drop_index(op.f('ix_submission_contest_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
