"""add_is_deleted_to_contest

Revision ID: ad20d28a34ef
Revises: cbe83273085d
Create Date: 2026-05-25 11:01:40.459682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad20d28a34ef'
down_revision = 'cbe83273085d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_contest_is_deleted'), 'contest', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_is_deleted'), table_name='contest')
    op.drop_column('contest', 'is_deleted')
    # ### end Alembic commands ###
