"""empty message

Revision ID: f2fc77413854
Revises: 6c5f4bc848f0
Create Date: 2026-05-20 15:54:21.917582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2fc77413854'
down_revision = '6c5f4bc848f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
